# Don't run Azure when a branch is updated, only when a PR is updated.
# Prevents double builds when a PR is made from the main repo and not a fork.
trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - '*'

pool:
  # self-hosted agent on Windows 10 2004 / WSL2 environment
  # includes Ruby 2.5
  name: Default

variables:
  COMPOSE_PROJECT_NAME: pupperware

workspace:
  clean: resources

steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  clean: true  # whether to fetch clean each time
- powershell: |
    . gem/ci/build.ps1
    Write-HostDiagnostics
  displayName: Diagnostic Host Information
  timeoutInMinutes: 2
  name: hostinfo

- powershell: |
    bundle install --with test --path '.bundle/gems'
  displayName: Fetch Dependencies
  timeoutInMinutes: 1
  name: fetch_deps

- powershell: |
    . gem/ci/build.ps1
    Initialize-TestEnv
  displayName: Prepare Test Environment
  name: test_prepare

- powershell: |
    . gem/ci/build.ps1
    Invoke-ContainerTest -Specs spec
  displayName: Test $(COMPOSE_PROJECT_NAME)
  timeoutInMinutes: 25
  name: test

- task: PublishTestResults@2
  displayName: Publish $(COMPOSE_PROJECT_NAME) test results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'TEST-rspec.xml'
    testRunTitle: $(COMPOSE_PROJECT_NAME) Test Results
  condition: always()

- powershell: |
    . gem/ci/build.ps1
    Clear-BuildState
  displayName: Build Cleanup
  timeoutInMinutes: 4
  condition: always()
