version: '3.7'
services:
  puppetboard:
    hostname: puppetboard.${DOMAIN:-test}
    image: voxpupuli/puppetboard:latest
    environment:
      - PUPPETDB_HOST=puppetdb
      - PUPPETDB_PORT=8081
      - INVENTORY_FACTS='Hostname,fqdn, IP Address,ipaddresss'      
      - ENABLE_CATALOG=True
      - GRAPH_FACTS='architecture,puppetversion,osfamily'
    ports:
      - 9080:80
    depends_on:
      - postgres
      - puppet
      - puppetdb
    dns_search: ${DOMAIN:-test}
    volumes:
      - puppetserver-config:/etc/puppetlabs/puppet/
    networks:
      default:
        aliases:
          - puppetboard.${DOMAIN:-test}
  puppetexplorer:
    hostname: puppetexplorer.${DOMAIN:-test}
    image: puppet/puppetexplorer
    ports:
      - 8001:80
    depends_on:
      - postgres
      - puppet
      - puppetdb
    read_only: true
    networks:
      default:
        aliases:
          - puppetexplorer.${DOMAIN:-test}
  puppet-catalog-diff-viewer:
    hostname: puppet-catalog-diff-viewer.${DOMAIN:-test}
    image: camptocamp/puppet-catalog-diff-viewer
    ports:
      - 8002:80
    depends_on:
      - postgres
      - puppet
      - puppetdb
    volumes:
      - puppet-catalog-diff-viewer:/data
    dns_search: ${DOMAIN:-test}
    networks:
      default:
        aliases:
          - puppet-catalog-diff-viewer.${DOMAIN:-test}
volumes:
  puppet-catalog-diff-viewer:
