version: '3.7'

services:
  puppet:
    hostname: puppet
    image: puppet/puppetserver:${PUPPETSERVER_VERSION:-latest}
    ports:
      - 8140:8140
    environment:
      # necessary to set certname and server in puppet.conf, required by
      # puppetserver ca cli application
      - PUPPETSERVER_HOSTNAME=puppet
      # DNS_ALT_NAMES must be set before starting the stack the first time,
      # and must list all the names under which the puppetserver can be
      # reached. Add other names as a comma-separated list
      - CA_ALLOW_SUBJECT_ALT_NAMES=true
      - DNS_ALT_NAMES=${DNS_ALT_NAMES:-}
      - PUPPERWARE_ANALYTICS_ENABLED=${PUPPERWARE_ANALYTICS_ENABLED:-true}
      - PUPPETDB_SERVER_URLS=https://puppetdb:8081
    volumes:
      - puppetserver-code:/etc/puppetlabs/code/
      - puppetserver-config:/etc/puppetlabs/puppet/
      - puppetserver-data:/opt/puppetlabs/server/data/puppetserver/

  postgres:
    image: postgres:9.6
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
      - POSTGRES_DB=puppetdb
    healthcheck:
      # existence check for puppetdb database
      test: [ 'CMD-SHELL', "psql --username=puppetdb puppetdb -c ''" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 2m
    expose:
      - 5432
    volumes:
      - puppetdb-postgres:/var/lib/postgresql/data
      - ./postgres-custom:/docker-entrypoint-initdb.d

  puppetdb:
    hostname: puppetdb
    image: puppet/puppetdb:${PUPPETDB_VERSION:-latest}
    environment:
      - PUPPERWARE_ANALYTICS_ENABLED=${PUPPERWARE_ANALYTICS_ENABLED:-true}
      # This name is an FQDN so the short name puppet doesn't collide outside compose network
      - PUPPETSERVER_HOSTNAME=puppet
      - PUPPETDB_POSTGRES_HOSTNAME=postgres
      - PUPPETDB_PASSWORD=puppetdb
      - PUPPETDB_USER=puppetdb
      - DNS_ALT_NAMES=${DNS_ALT_NAMES:-}
    ports:
      - 8080
      - 8081
    depends_on:
      - postgres
      - puppet
    volumes:
      - puppetdb:/opt/puppetlabs/server/data/puppetdb

volumes:
  puppetserver-code:
  puppetserver-config:
  puppetserver-data:
  puppetdb:
  puppetdb-postgres:
